Added CipherTrust Tokenization Server README.md
thalescpl-io/CipherTrust_Application_Protection pull request #2
Opened 2020-09-04 13:56 UTC by vinaynegi25

Please review the CipherTrust Tokenization Server README.md and api.md.

2020-09-04 18:56 UTC, alvinabad commented on Tokenization_Samples/README.md
> +Header: {'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '_/_', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Content-Length': '104', 'Authori
Please remove passwords.

2020-09-04 18:56 UTC, alvinabad commented on Tokenization_Samples/README.md
> +$ python detokenize.py -d -u root:ca\$hcow -l https://192.0.2.0/vts -I token -O raw -tg FF1_Tok_Group -tt FF1_Tok_Template
Please remove password.

2020-09-14 16:45 UTC, alvinabad requested changes

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +## tokenize
Maybe rename this to something like "Tokenization Samples" to avoid the keyword VTS.

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +**tokengroup** : `Defines a group name space in the configuration database. The VTS GUI Administrator must create token groups that match the tokengroup parameter names used in the application code.`
Maybe rename "The VTS GUI Administrator" to "Tokenization Server Administrator"  to avoid the VTS keyword.

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +**tokengroup** : `Defines a group name space in the configuration database. The VTS GUI Administrator must create token groups that match the tokengroup parameter names used in the application code.`
Maybe rename "The VTS GUI Administrator" to "Tokenization Server Administrator" to avoid the VTS keyword.

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +**tokentemplate** : `VTS GUI Administrator-defined name for a group of properties that define tokenization operation.`
Maybe rename "The VTS GUI Administrator" to "Tokenization Server Administrator" to avoid the VTS keyword.

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +$ python tokenize.py -d -u <username>:<password> -l https://192.0.2.0/vts -p DataToTokenizeDetokenize -O token -tg FF1_Tok_Group -tt FF1_Tok_Template
Minor only:

How come the input is a URL? It should simply be an IP address or hostname of the Tokenization server. The scheme (https) and the "/vts" path of the URL should be hidden from the user and simply included in the URL of endpoint in your sample program altogether.

For example, the official REST-API endpoint of tokenize is this URL path:
/vts/rest/v2.0/tokenize

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +**github link** : https://github.com/thalescpl-io/CipherTrust_Application_Protection/blob/TOK-2779/Tokenization_Samples/detokenize.py
Will this be a link to the private branch instead of the master?

2020-09-14 16:45 UTC, alvinabad commented on Tokenization_Samples/README.md
> +https://github.com/thalescpl-io/CipherTrust_Application_Protection/blob/TOK-2779/Tokenization_Samples/api.md
Will this be a link to the private branch instead of the master?

2020-09-24 05:07 UTC, PrashantChaudhari-Github requested changes

2020-09-24 05:07 UTC, PrashantChaudhari-Github commented on README.md
> +**Tokenization service**
Remove bold formatting or use smaller size font for sub topics

2020-09-24 05:07 UTC, PrashantChaudhari-Github commented on Tokenization_Samples/README.md
> +# VTS samples
Add pre-requisites needed to run these samples- CipherTrust Manager, CTS, python version etc.

2020-09-24 20:43 UTC, alvinabad approved these changes

2020-09-28 04:39 UTC, merged

2020-10-19 09:15 UTC, rthalesgit commented on Tokenization_Samples/python_samples/README.md
> +
Python Samples have samples for Tokenize and Detokenize while Java samples have samples for "Tokenize/detokenize" and "Tokenize/detokenize Bulk mode". Can we please make this symmetric for both. 

Review comments for Java sample page( As I cant find link to add review comments for it):

- Title to be "JavaTokenization Samples"
- Font correction for "Output"
- Move REST API link to main page and remove from each

2020-10-19 09:15 UTC, rthalesgit commented on Tokenization_Samples/python_samples/README.md
> +## Tokenization/Detokenization api details
We can move this to main page and remove from here.

2020-10-19 09:15 UTC, rthalesgit commented on Tokenization_Samples/python_samples/README.md
> +$ python tokenize.py -d -u <username>:<password> -l <vts URL> -p <data or plaintext string> -O <outputFile> -tg <tokengroup> -tt <tokentemplate>
<cts URL>

2020-10-19 09:15 UTC, rthalesgit commented on Tokenization_Samples/python_samples/README.md
> +$ python detokenize.py -d -u <username>:<password> -l <vts URL> -I <inputFile> -O <outputFile> -tg <tokengroup> -tt <tokentemplate>
<cts URL>